# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Build-$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
jobs:
  - job: Build
    steps:
    - task: Bash@3
      name: Gradle_build
      displayName: Gradle build
      inputs:
        targetType: 'inline'
        script: |
          echo ('=========== Gradle build start ==============')
          #sh "gradle clean build copyDriversToBuild"
          echo "=========== In Progress =============="  
          echo "=========== Finish =============="
      env:
        BUILD_ID: $(Build.BuildId)